# wandb
wandb:
  name: "resnet50_09CrossEntropyLoss+01Triplet_500"  # Optional, could be left empty for random name
  project: "hw2p2-ablations"
  wandb_api_key: "46b9373c96fe8f8327255e7da8a4046da7ffeef6"

# folder path
data_dir: "./data/11-785-f24-hw2p2-verification/cls_data"
data_ver_dir: "./data/11-785-f24-hw2p2-verification/ver_data"
val_pairs_file: "./data/11-785-f24-hw2p2-verification/val_pairs.txt"
test_pairs_file: './data/11-785-f24-hw2p2-verification/test_pairs.txt'
checkpoint_dir: "./checkpoints"



resume:
  resume: false
  id: '1727409915'


# Parameters
batch_size: 64
epochs: 500
e: 0

# Optimizer parameters
optimizer:
  type: 'AdamW'  # 'AdamW' or 'SGD'
  lr: 0.01
  weight_decay: 0.01
  momentum: 0.9  # This is for SGD

# Scheduler parameters
scheduler:
  type: 'CosineAnnealingLR'  # 'CosineAnnealingLR' or 'CosineAnnealingWarmRestarts'
  T_max: 500  # For CosineAnnealingLR

  T_0: 40 # For CosineAnnealingWarmRestarts
  T_mult: 2 # For CosineAnnealingWarmRestarts
  eta_min: 0 # For CosineAnnealingWarmRestarts
